### ISSUE TITLE
Moto G Play (2021) [guamna] has decoding problems with 10-bit HEVC

### ISSUE THREAD

**Issue by Pentaphon** [MotorolaMobilityLLC/kernel-msm-techpack-video#1]
Steps: 
1) Download https://jell.yfish.us/media/jellyfish-10-mbps-hd-hevc-10bit.mkv
2) Play it on https://play.google.com/store/apps/details?id=com.brouken.player&hl=en_US&gl=US
3) Won't play, see screenshot below for error you get. 

![Screenshot_20211206-022642](https://user-images.githubusercontent.com/49374058/144830696-9443dcc1-5f4f-4c51-8fbf-1f2139c41cfc.png)

**Comment by mbissaromoto** [comment]
Duplicated of https://github.com/MotorolaMobilityLLC/kernel-msm/issues/388
